export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS app_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    avatar_url TEXT,
    created_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS user_profiles (
    user_id TEXT PRIMARY KEY,
    role TEXT NOT NULL DEFAULT '',
    organization TEXT NOT NULL DEFAULT '',
    bio TEXT NOT NULL DEFAULT '',
    active_ai_provider_id TEXT NOT NULL DEFAULT 'environment',
    updated_at TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS ai_providers (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    provider_type TEXT NOT NULL DEFAULT 'openai-compatible',
    base_url TEXT NOT NULL,
    api_mode TEXT NOT NULL CHECK (api_mode IN ('responses', 'chat_completions')),
    model TEXT NOT NULL,
    encrypted_token TEXT NOT NULL DEFAULT '',
    token_hint TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(user_id, name),
    FOREIGN KEY(user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS repositories (
    id TEXT PRIMARY KEY,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    open_pull_count INTEGER NOT NULL DEFAULT 0,
    open_issue_count INTEGER NOT NULL DEFAULT 0,
    last_synced_at TEXT,
    sync_status TEXT NOT NULL DEFAULT 'idle',
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS community_items (
    id TEXT PRIMARY KEY,
    repo_id TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('pr', 'issue')),
    number INTEGER NOT NULL,
    state TEXT NOT NULL,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    author_avatar TEXT,
    body_md TEXT NOT NULL DEFAULT '',
    html_url TEXT,
    comments INTEGER NOT NULL DEFAULT 0,
    domain TEXT NOT NULL DEFAULT 'Other',
    ai_summary TEXT NOT NULL DEFAULT '',
    status_text TEXT NOT NULL DEFAULT '',
    important INTEGER NOT NULL DEFAULT 0,
    created_at TEXT,
    updated_at TEXT NOT NULL,
    merged_at TEXT,
    closed_at TEXT,
    is_draft INTEGER NOT NULL DEFAULT 0,
    content_hash TEXT NOT NULL DEFAULT '',
    summary_input_hash TEXT NOT NULL DEFAULT '',
    summary_source TEXT NOT NULL DEFAULT 'excerpt',
    summary_updated_at TEXT,
    fetched_at TEXT NOT NULL,
    diff_json TEXT,
    diff_files_count INTEGER NOT NULL DEFAULT 0,
    additions INTEGER NOT NULL DEFAULT 0,
    deletions INTEGER NOT NULL DEFAULT 0,
    domain_source TEXT NOT NULL DEFAULT 'text',
    domain_confidence REAL NOT NULL DEFAULT 0,
    domain_evidence_json TEXT NOT NULL DEFAULT '{}',
    review_signal_json TEXT NOT NULL DEFAULT '{}',
    review_signal_updated_at TEXT,
    UNIQUE(repo_id, kind, number),
    FOREIGN KEY(repo_id) REFERENCES repositories(id)
  )`,
  `CREATE TABLE IF NOT EXISTS community_events (
    id TEXT PRIMARY KEY,
    repo_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    event_type TEXT NOT NULL CHECK (
      event_type IN (
        'opened', 'updated', 'draft', 'ready_for_review',
        'merged', 'closed', 'reopened'
      )
    ),
    occurred_at TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'sync',
    actor TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    UNIQUE(item_id, event_type, occurred_at),
    FOREIGN KEY(repo_id) REFERENCES repositories(id),
    FOREIGN KEY(item_id) REFERENCES community_items(id)
  )`,
  `CREATE TABLE IF NOT EXISTS cross_repo_impacts (
    id TEXT PRIMARY KEY,
    source_item_id TEXT NOT NULL,
    target_repo_id TEXT NOT NULL,
    domain TEXT NOT NULL,
    level TEXT NOT NULL CHECK (level IN ('low', 'medium', 'high', 'critical')),
    status TEXT NOT NULL CHECK (
      status IN (
        'unreviewed', 'possibly_affected', 'needs_adaptation',
        'in_progress', 'adapted', 'not_applicable'
      )
    ),
    analysis TEXT NOT NULL,
    changed_paths_json TEXT NOT NULL DEFAULT '[]',
    target_paths_json TEXT NOT NULL DEFAULT '[]',
    related_item_id TEXT,
    evidence_json TEXT NOT NULL DEFAULT '[]',
    generated_by TEXT NOT NULL DEFAULT 'rules',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(source_item_id, target_repo_id),
    FOREIGN KEY(source_item_id) REFERENCES community_items(id),
    FOREIGN KEY(target_repo_id) REFERENCES repositories(id),
    FOREIGN KEY(related_item_id) REFERENCES community_items(id)
  )`,
  `CREATE TABLE IF NOT EXISTS watchlist (
    user_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    reason TEXT NOT NULL DEFAULT '持续关注',
    note TEXT NOT NULL DEFAULT '',
    priority TEXT NOT NULL DEFAULT 'P2',
    next_check TEXT,
    created_at TEXT NOT NULL,
    PRIMARY KEY(user_id, item_id),
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(item_id) REFERENCES community_items(id)
  )`,
  `CREATE TABLE IF NOT EXISTS analysis_documents (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    scope TEXT NOT NULL,
    title TEXT NOT NULL,
    summary_md TEXT NOT NULL DEFAULT '',
    content_md TEXT NOT NULL,
    prompt TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'ready',
    created_by TEXT,
    source_refs_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(created_by) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS domain_snapshots (
    id TEXT PRIMARY KEY,
    domain TEXT NOT NULL,
    snapshot_date TEXT NOT NULL,
    architecture_md TEXT NOT NULL,
    changed_paths_json TEXT NOT NULL DEFAULT '[]',
    activity_json TEXT NOT NULL DEFAULT '{}',
    insight_md TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    UNIQUE(domain, snapshot_date)
  )`,
  `CREATE TABLE IF NOT EXISTS technical_documents (
    id TEXT PRIMARY KEY,
    category TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    content_md TEXT NOT NULL,
    tags_json TEXT NOT NULL DEFAULT '[]',
    source_refs_json TEXT NOT NULL DEFAULT '[]',
    author_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(author_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS chat_threads (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    context_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS chat_messages (
    id TEXT PRIMARY KEY,
    thread_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content_md TEXT NOT NULL,
    context_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    FOREIGN KEY(thread_id) REFERENCES chat_threads(id)
  )`,
  `CREATE TABLE IF NOT EXISTS sync_runs (
    id TEXT PRIMARY KEY,
    repo_id TEXT NOT NULL,
    status TEXT NOT NULL,
    item_count INTEGER NOT NULL DEFAULT 0,
    error TEXT,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    FOREIGN KEY(repo_id) REFERENCES repositories(id)
  )`,
] as const;

export const indexStatements = [
  "CREATE INDEX IF NOT EXISTS community_repo_kind_updated_idx ON community_items(repo_id, kind, updated_at DESC)",
  "CREATE INDEX IF NOT EXISTS community_domain_updated_idx ON community_items(domain, updated_at DESC)",
  "CREATE INDEX IF NOT EXISTS community_events_repo_occurred_idx ON community_events(repo_id, occurred_at DESC)",
  "CREATE INDEX IF NOT EXISTS community_events_item_occurred_idx ON community_events(item_id, occurred_at DESC)",
  "CREATE INDEX IF NOT EXISTS impacts_target_updated_idx ON cross_repo_impacts(target_repo_id, updated_at DESC)",
  "CREATE INDEX IF NOT EXISTS analyses_type_updated_idx ON analysis_documents(type, updated_at DESC)",
  "CREATE INDEX IF NOT EXISTS docs_category_updated_idx ON technical_documents(category, updated_at DESC)",
  "CREATE INDEX IF NOT EXISTS messages_thread_created_idx ON chat_messages(thread_id, created_at ASC)",
  "CREATE INDEX IF NOT EXISTS domain_snapshot_date_idx ON domain_snapshots(snapshot_date DESC)",
  "CREATE INDEX IF NOT EXISTS ai_providers_user_updated_idx ON ai_providers(user_id, updated_at DESC)",
] as const;
